#priority 40
import crafttweaker.item.IItemStack;

// ================================================================================
// Arcana Quest: HungerTweaker Food Values & Always-Edible Desserts
// Rebalanced nutritional scaling across Vanilla, Rustic, Bewitchment, Roots,
// Mystical World, Farmer's Delight, Extra Delight, Nether's Delight,
// End's Delight, and Twilight Delight.
// Note: Only hand-eaten food items are modified. Multi-portion placeable feast
// blocks (ItemBlocks) are excluded as they cannot be eaten directly.
// ================================================================================

val foodOverrides as float[][IItemStack] = {
    // ============================================================
    // === TIER 0: DRINKS & BREWS (0 Hunger / 0.0 Saturation) ===
    // ============================================================
    <farmersdelight:apple_cider>: [0.0, 0.0],
    <farmersdelight:hot_cocoa>: [0.0, 0.0],
    <farmersdelight:milk_bottle>: [0.0, 0.0],
    <farmersdelight:melon_juice>: [0.0, 0.0],
    <extradelightlegacy:soy_milk>: [0.0, 0.0],
    <extradelightlegacy:chocolate_milk>: [0.0, 0.0],
    <extradelightlegacy:eggnog>: [0.0, 0.0],
    <extradelightlegacy:punch>: [0.0, 0.0],
    <extradelightlegacy:sweet_berry_juice>: [0.0, 0.0],
    <bewitchment:juniper_tea>: [0.0, 0.0],
    <animania:milk_bottle>: [0.0, 0.0],
    <twilightdelight:tear_drink>: [0.0, 0.0],
    <twilightdelight:milky_113>: [0.0, 0.0],
    <twilightdelight:glacier_ice_tea>: [0.0, 0.0],
    <twilightdelight:thorn_rose_tea>: [0.0, 0.0],
    <twilightdelight:phytochemical_juice>: [0.0, 0.0],
    <twilightdelight:torchberry_juice>: [0.0, 0.0],
    <twilightdelight:twilight_spring>: [0.0, 0.0],
    <ends_delight:bubble_tea>: [0.0, 0.0],
    <ends_delight:chorus_flower_tea>: [0.0, 0.0],
    <ends_delight:chorus_fruit_milk_tea>: [0.0, 0.0],
    <ends_delight:chorus_fruit_wine>: [0.0, 0.0],
    <contenttweaker:bottled_black_tea>: [0.0, 0.0],
    <contenttweaker:bottled_green_tea>: [0.0, 0.0],
    <contenttweaker:bottled_white_tea>: [0.0, 0.0],
    <contenttweaker:bottled_yellow_tea>: [0.0, 0.0],
    <contenttweaker:bottled_lemon_tea>: [0.0, 0.0],
    <contenttweaker:bottled_milk_tea>: [0.0, 0.0],
    <contenttweaker:bottled_black_infused_tea_base>: [0.0, 0.0],
    <contenttweaker:bottled_white_infused_tea_base>: [0.0, 0.0],

    // ============================================================
    // === TIER 1: FORAGE, RAW CROPS & RAW SCRAPS (1 - 2 Hunger / 0.2 - 0.4 Sat) ===
    // ============================================================
    <minecraft:apple>: [2.0, 0.3],
    <minecraft:carrot>: [2.0, 0.3],
    <minecraft:potato>: [1.0, 0.2],
    <minecraft:melon>: [2.0, 0.3],
    <minecraft:chorus_fruit>: [2.0, 0.3],
    <minecraft:beetroot>: [1.0, 0.2],
    <rustic:wildberries>: [1.0, 0.3],
    <rustic:ironberries>: [1.0, 0.25],
    <rustic:cloudsbluff>: [1.0, 0.25],
    <rustic:core_root>: [1.0, 0.3],
    <rustic:ginseng>: [1.0, 0.3],
    <rustic:marsh_mallow>: [2.0, 0.3],
    <rustic:tomato>: [1.0, 0.3],
    <rustic:chili_pepper>: [1.0, 0.3],
    <mysticalworld:aubergine>: [2.0, 0.3],
    <farmersdelight:cabbage_leaf>: [1.0, 0.3],
    <farmersdelight:pumpkin_slice>: [2.0, 0.3],
    <farmersdelight:onion>: [2.0, 0.3],
    <farmersdelight:cabbage>: [2.0, 0.3],
    <farmersdelight:chicken_cuts>: [1.0, 0.25],
    <farmersdelight:bacon>: [2.0, 0.3],
    <farmersdelight:cod_slice>: [1.0, 0.2],
    <farmersdelight:salmon_slice>: [1.0, 0.2],
    <farmersdelight:mutton_chops>: [2.0, 0.3],
    <extradelightlegacy:beef_scraps>: [1.0, 0.25],
    <extradelightlegacy:pork_scraps>: [1.0, 0.25],
    <extradelightlegacy:lamb_scraps>: [1.0, 0.25],
    <extradelightlegacy:goat_scraps>: [1.0, 0.25],
    <extradelightlegacy:chicken_scraps>: [1.0, 0.25],
    <extradelightlegacy:cubed_beef>: [2.0, 0.3],
    <extradelightlegacy:cubed_pork>: [2.0, 0.3],
    <extradelightlegacy:cubed_lamb>: [2.0, 0.3],
    <extradelightlegacy:cubed_goat>: [2.0, 0.3],
    <extradelightlegacy:ground_beef>: [2.0, 0.3],
    <extradelightlegacy:ground_pork>: [2.0, 0.3],
    <extradelightlegacy:ground_lamb>: [2.0, 0.3],
    <extradelightlegacy:ground_goat>: [2.0, 0.3],
    <extradelightlegacy:sliced_onion>: [1.0, 0.3],
    <extradelightlegacy:sliced_apple>: [1.0, 0.3],
    <extradelightlegacy:potato_sticks>: [1.0, 0.25],
    <extradelightlegacy:bread_slice>: [2.0, 0.3],
    <extradelightlegacy:garlic_clove>: [1.0, 0.3],
    <extradelightlegacy:peeled_ginger>: [1.0, 0.3],
    <extradelightlegacy:peanuts>: [1.0, 0.25],
    <nethers_delight_legacy:hoglin_loin>: [2.0, 0.25],
    <ends_delight:raw_ender_mite_meat>: [2.0, 0.2],
    <ends_delight:shulker_meat>: [2.0, 0.25],
    <ends_delight:shulker_meat_slice>: [1.0, 0.2],
    <ends_delight:ender_pearl_grain>: [1.0, 0.2],
    <ends_delight:chorus_fruit_grain>: [1.0, 0.2],
    <twilightdelight:raw_meef_slice>: [2.0, 0.25],
    <twilightdelight:raw_venison_rib>: [2.0, 0.25],
    <twilightdelight:raw_insect>: [2.0, 0.2],
    <minecraft:cookie>: [2.0, 0.25],
    <farmersdelight:sweet_berry_cookie>: [2.0, 0.25],
    <farmersdelight:honey_cookie>: [2.0, 0.3],
    <ends_delight:chorus_cookie>: [2.0, 0.25],
    <twilightdelight:torchberry_cookie>: [2.0, 0.25],

    // ============================================================
    // === TIER 2: QUICK BITES, COOKED CUTS & SCRAPS (3 - 4 Hunger / 0.4 - 0.6 Sat) ===
    // ============================================================
    <minecraft:baked_potato>: [3.0, 0.5],
    <farmersdelight:ham>: [4.0, 0.5],
    <farmersdelight:cooked_chicken_cuts>: [3.0, 0.5],
    <farmersdelight:cooked_bacon>: [4.0, 0.6],
    <farmersdelight:cooked_cod_slice>: [3.0, 0.5],
    <farmersdelight:cooked_salmon_slice>: [3.0, 0.5],
    <farmersdelight:beef_patty>: [4.0, 0.6],
    <farmersdelight:cooked_rice>: [4.0, 0.5],
    <farmersdelight:fried_egg>: [4.0, 0.5],
    <extradelightlegacy:cooked_beef_scraps>: [3.0, 0.5],
    <extradelightlegacy:cooked_pork_scraps>: [3.0, 0.5],
    <extradelightlegacy:cooked_lamb_scraps>: [3.0, 0.5],
    <extradelightlegacy:cooked_goat_scraps>: [3.0, 0.5],
    <extradelightlegacy:cooked_chicken_scraps>: [3.0, 0.5],
    <extradelightlegacy:cooked_ground_beef>: [3.0, 0.5],
    <extradelightlegacy:cooked_ground_pork>: [3.0, 0.5],
    <extradelightlegacy:cooked_ground_lamb>: [3.0, 0.5],
    <extradelightlegacy:cooked_ground_goat>: [3.0, 0.5],
    <extradelightlegacy:cooked_cubed_beef>: [4.0, 0.6],
    <extradelightlegacy:cooked_cubed_pork>: [4.0, 0.6],
    <extradelightlegacy:cooked_cubed_lamb>: [4.0, 0.6],
    <extradelightlegacy:cooked_cubed_goat>: [4.0, 0.6],
    <extradelightlegacy:grilled_corn_on_cob>: [4.0, 0.5],
    <extradelightlegacy:roll>: [3.0, 0.5],
    <extradelightlegacy:toast>: [3.0, 0.5],
    <extradelightlegacy:roasted_peanuts>: [3.0, 0.4],
    <extradelightlegacy:roasted_hazelnuts>: [3.0, 0.4],
    <extradelightlegacy:roasted_pumpkin_seeds>: [3.0, 0.4],
    <extradelightlegacy:grilled_grapefruit>: [3.0, 0.5],
    <extradelightlegacy:stuffed_mushrooms>: [4.0, 0.5],
    <extradelightlegacy:trail_mix>: [4.0, 0.5],
    <nethers_delight_legacy:ground_strider>: [3.0, 0.5],
    <nethers_delight_legacy:hoglin_ear>: [3.0, 0.4],
    <nethers_delight_legacy:magma_gelatin>: [4.0, 0.5],
    <ends_delight:dried_endermite_meat>: [3.0, 0.5],
    <ends_delight:chorus_sauce>: [3.0, 0.4],
    <ends_delight:raw_ender_sausage>: [3.0, 0.4],
    <twilightdelight:cooked_insect>: [3.0, 0.5],
    <twilightdelight:fried_insect>: [4.0, 0.5],
    <twilightdelight:chocolate_wafer>: [3.0, 0.4],
    <twilightdelight:berry_stick>: [4.0, 0.5],
    <twilightdelight:naga_chip>: [3.0, 0.5],
    <twilightdelight:experiment_113>: [4.0, 0.5],

    // ============================================================
    // === TIER 3: HANDHELDS, COOKED CUTS, LOAVES, ARTISAN SLICES & PASTRIES ===
    // === (6 - 8 Hunger / 0.6 - 0.75 Sat) — Slices match Bread (7.0 / 0.7) ===
    // ============================================================
    <minecraft:bread>: [7.0, 0.7],
    <extradelightlegacy:cornbread>: [7.0, 0.7],
    <farmersdelight:smoked_ham>: [8.0, 0.8],
    <farmersdelight:cooked_mutton_chops>: [6.0, 0.7],
    <farmersdelight:egg_sandwich>: [6.0, 0.7],
    <farmersdelight:chicken_sandwich>: [8.0, 0.75],
    <farmersdelight:bacon_sandwich>: [8.0, 0.75],
    <farmersdelight:mutton_wrap>: [8.0, 0.75],
    <farmersdelight:cabbage_rolls>: [6.0, 0.65],
    <farmersdelight:salmon_roll>: [7.0, 0.7],
    <farmersdelight:cod_roll>: [7.0, 0.7],
    <farmersdelight:kelp_roll>: [7.0, 0.7],
    <farmersdelight:kelp_roll_slice>: [6.0, 0.65],
    <farmersdelight:stuffed_potato>: [8.0, 0.75],
    <extradelightlegacy:cinnamon_rolls>: [7.0, 0.7],
    <extradelightlegacy:pumpkin_roll>: [7.0, 0.7],
    <extradelightlegacy:apple_crisp>: [7.0, 0.7],
    <extradelightlegacy:stuffed_apple>: [7.0, 0.7],
    <extradelightlegacy:lava_cake>: [7.0, 0.7],
    <farmersdelight:bone_broth>: [6.0, 0.65],
    <farmersdelight:fruit_salad>: [6.0, 0.65],
    <farmersdelight:mixed_salad>: [6.0, 0.65],
    <farmersdelight:nether_salad>: [6.0, 0.65],
    <extradelightlegacy:cooked_beef_stewmeat>: [6.0, 0.7],
    <extradelightlegacy:cooked_pork_stewmeat>: [6.0, 0.7],
    <extradelightlegacy:cooked_lamb_stewmeat>: [6.0, 0.7],
    <extradelightlegacy:cooked_goat_stewmeat>: [6.0, 0.7],
    <extradelightlegacy:cooked_chicken_breast>: [7.0, 0.7],
    <extradelightlegacy:cooked_chicken_leg>: [6.0, 0.65],
    <extradelightlegacy:cooked_chicken_thigh>: [7.0, 0.7],
    <extradelightlegacy:cooked_beef_ribs>: [7.0, 0.75],
    <extradelightlegacy:cooked_pork_ribs>: [7.0, 0.75],
    <extradelightlegacy:cooked_lamb_ribs>: [7.0, 0.75],
    <extradelightlegacy:egg_in_the_basket>: [7.0, 0.75],
    <extradelightlegacy:french_toast>: [7.0, 0.75],
    <extradelightlegacy:honey_custard>: [6.0, 0.65],
    <extradelightlegacy:honey_ice_cream>: [6.0, 0.5],
    <extradelightlegacy:mint_chip_ice_cream>: [6.0, 0.5],
    <bewitchment:garlic_bread>: [7.0, 0.75],
    <mysticalworld:epic_squid>: [8.0, 0.75],
    <xreliquary:glowing_bread>: [8.0, 0.75],
    <lycanitesmobs:searing_taco>: [8.0, 0.75],
    <lycanitesmobs:seashell_maki>: [7.0, 0.7],
    <twilightdelight:honey_113>: [6.0, 0.65],
    <nethers_delight_legacy:hoglin_sirloin>: [7.0, 0.7],
    <nethers_delight_legacy:strider_slice>: [6.0, 0.65],
    <nethers_delight_legacy:nether_skewer>: [7.0, 0.7],
    <ends_delight:roasted_shulker_meat>: [6.0, 0.7],
    <ends_delight:roasted_shulker_meat_slice>: [6.0, 0.65],
    <ends_delight:stuffed_rice_cake>: [6.0, 0.65],
    <ends_delight:assorted_salad>: [6.0, 0.65],
    <ends_delight:end_mixed_salad>: [6.0, 0.65],
    <ends_delight:end_barbecue_stick>: [7.0, 0.7],
    <twilightdelight:cooked_meef_slice>: [6.0, 0.7],
    <twilightdelight:cooked_venison_rib>: [6.0, 0.7],
    <twilightdelight:cooked_tomahawk_smeak>: [8.0, 0.8],
    <twilightdelight:torchberry_venison_sandwich>: [8.0, 0.75],
    <twilightdelight:meef_wrap>: [8.0, 0.75],
    <twilightdelight:aurora_ice_cream>: [6.0, 0.5],
    <twilightdelight:torchberry_ice_cream>: [6.0, 0.5],
    <twilightdelight:phytochemical_ice_cream>: [6.0, 0.5],
    <twilightdelight:glacier_ice_cream>: [6.0, 0.5],

    // Cake & Cheesecake Slices (Tier 3: 7.0 Hunger / 0.7 Saturation)
    <farmersdelight:cake_slice>: [7.0, 0.7],
    <farmersdelight:sweet_berry_cheesecake_slice>: [7.0, 0.7],
    <extradelightlegacy:cheesecake_slice>: [7.0, 0.7],
    <extradelightlegacy:apple_cheesecake_slice>: [7.0, 0.7],
    <extradelightlegacy:caramel_cheesecake_slice>: [7.0, 0.7],
    <extradelightlegacy:chocolate_cheesecake_slice>: [7.0, 0.7],
    <extradelightlegacy:glow_berry_cheesecake_slice>: [7.0, 0.7],
    <extradelightlegacy:honey_cheesecake_slice>: [7.0, 0.7],
    <extradelightlegacy:pumpkin_cheesecake_slice>: [7.0, 0.7],
    <extradelightlegacy:chocolate_cake_slice>: [7.0, 0.7],
    <twilightdelight:aurora_cake_slice>: [7.0, 0.7],
    <twilightdelight:torchberry_cake_slice>: [7.0, 0.7],
    <twilightdelight:phytochemical_cake_slice>: [7.0, 0.7],
    <twilightdelight:glacier_cake_slice>: [7.0, 0.7],

    // Sweet Pie Slices (Tier 3: 7.0 Hunger / 0.7 Saturation)
    <farmersdelight:apple_pie_slice>: [7.0, 0.7],
    <farmersdelight:chocolate_pie_slice>: [7.0, 0.7],
    <farmersdelight:pumpkin_pie_slice>: [7.0, 0.7],
    <extradelightlegacy:sweet_berry_pie_slice>: [7.0, 0.7],
    <extradelightlegacy:glow_berry_pie_slice>: [7.0, 0.7],
    <extradelightlegacy:pumpkin_pie_slice>: [7.0, 0.7],
    <ends_delight:chorus_fruit_pie_slice>: [7.0, 0.7],
    <twilightdelight:torchberry_pie_slice>: [7.0, 0.7],
    <twilightdelight:aurora_pie_slice>: [7.0, 0.7],

    // Savory Pie Slices (Tier 3: 7.0 Hunger / 0.7 Saturation)
    <extradelightlegacy:bacon_egg_pie_slice>: [7.0, 0.7],
    <extradelightlegacy:meat_pie_slice>: [7.0, 0.7],
    <extradelightlegacy:steak_pickled_onion_pie_slice>: [7.0, 0.7],

    // ============================================================
    // === TIER 4: PLATED BOWLS, SKILLETS & STEWS (10 - 13 Hunger / 0.8 - 0.95 Sat) ===
    // === Primary Triggers for Well Fed / Nourishment & Comfort ===
    // ============================================================
    <farmersdelight:beef_stew>: [12.0, 0.9],
    <farmersdelight:vegetable_soup>: [10.0, 0.85],
    <farmersdelight:fish_stew>: [11.0, 0.85],
    <farmersdelight:chicken_soup>: [12.0, 0.9],
    <farmersdelight:fried_rice>: [11.0, 0.85],
    <farmersdelight:pumpkin_soup>: [10.0, 0.85],
    <farmersdelight:baked_cod_stew>: [11.0, 0.85],
    <farmersdelight:noodle_soup>: [11.0, 0.85],
    <farmersdelight:bacon_and_eggs>: [10.0, 0.85],
    <farmersdelight:ratatouille>: [10.0, 0.85],
    <farmersdelight:steak_and_potatoes>: [12.0, 0.9],
    <farmersdelight:pasta_with_meatballs>: [12.0, 0.9],
    <farmersdelight:pasta_with_mutton_chop>: [12.0, 0.9],
    <farmersdelight:mushroom_rice>: [11.0, 0.85],
    <farmersdelight:grilled_salmon>: [12.0, 0.9],
    <farmersdelight:roasted_mutton_chops>: [12.0, 0.9],
    <farmersdelight:vegetable_noodles>: [11.0, 0.85],
    <farmersdelight:squid_ink_pasta>: [12.0, 0.9],
    <farmersdelight:dumplings>: [10.0, 0.85],
    <extradelightlegacy:cooked_beef_roast>: [12.0, 0.9],
    <extradelightlegacy:cooked_pork_roast>: [12.0, 0.9],
    <extradelightlegacy:cooked_lamb_roast>: [12.0, 0.9],
    <extradelightlegacy:cooked_goat_roast>: [12.0, 0.9],
    <extradelightlegacy:bacon_egg_pie>: [11.0, 0.85],
    <extradelightlegacy:meat_pie>: [11.0, 0.85],
    <extradelightlegacy:steak_pickled_onion_pie>: [12.0, 0.9],
    <extradelightlegacy:honey_chili_chicken>: [12.0, 0.9],
    <extradelightlegacy:corn_pudding>: [12.0, 0.9],
    <extradelightlegacy:stuffing>: [12.0, 0.9],
    <nethers_delight_legacy:strider_moss_stew>: [11.0, 0.85],
    <nethers_delight_legacy:grilled_strider>: [12.0, 0.9],
    <ends_delight:roasted_dragon_meat>: [12.0, 0.9],
    <ends_delight:roasted_dragon_meat_cuts>: [11.0, 0.85],
    <ends_delight:smoked_dragon_leg>: [12.0, 0.9],
    <ends_delight:dragon_breath_and_chorus_soup>: [12.0, 0.9],
    <ends_delight:shulker_soup>: [11.0, 0.85],
    <ends_delight:enderman_gristle_stew>: [11.0, 0.85],
    <ends_delight:ender_congee>: [11.0, 0.85],
    <ends_delight:ender_noodle>: [11.0, 0.85],
    <ends_delight:ender_bamboo_rice>: [11.0, 0.85],
    <ends_delight:stir_fried_shulker_meat>: [12.0, 0.9],
    <twilightdelight:glowstew>: [11.0, 0.85],
    <twilightdelight:borer_tear_soup>: [11.0, 0.85],
    <twilightdelight:thousand_plant_stew>: [12.0, 0.9],
    <twilightdelight:liveroot_venison_noodle_soup>: [12.0, 0.9],
    <twilightdelight:ghast_brain_salad>: [10.0, 0.85],
    <twilightdelight:glow_venison_rib_with_pasta>: [13.0, 0.95],
    <twilightdelight:mushgloom_meef_pasta>: [13.0, 0.95],
    <twilightdelight:liveroot_pork_fried_rice>: [12.0, 0.9],
    <twilightdelight:grilled_ghast>: [12.0, 0.9],
    <twilightdelight:grilled_tomahawk_smeak>: [13.0, 0.95],

    // ============================================================
    // === TIER 5: SAVORY FEASTS & BANQUETS (14 - 20 Hunger / 0.95 - 1.2 Sat) ===
    // === Multi-Portion Savory Feast Bowl & Plate Servings ===
    // ============================================================
    <nethers_delight_legacy:plate_of_stuffed_hoglin_snout>: [14.0, 0.9],
    <nethers_delight_legacy:plate_of_stuffed_hoglin_ham>: [14.0, 0.9],
    <nethers_delight_legacy:plate_of_stuffed_hoglin_roast>: [16.0, 1.0],
    <farmersdelight:roast_chicken>: [16.0, 1.0],
    <farmersdelight:stuffed_pumpkin>: [16.0, 1.0],
    <farmersdelight:honey_glazed_ham>: [18.0, 1.1],
    <farmersdelight:shepherds_pie>: [18.0, 1.1],
    <ends_delight:steamed_dragon_egg>: [16.0, 1.0],
    <ends_delight:dragon_meat_stew>: [18.0, 1.1],
    <ends_delight:dragon_leg_with_sauce>: [18.0, 1.1],
    <ends_delight:grilled_shulker>: [15.0, 0.95],
    <twilightdelight:fiery_snakes>: [16.0, 1.0],
    <twilightdelight:lily_chicken>: [16.0, 1.0],
    <twilightdelight:plate_of_meef_wellington>: [18.0, 1.1]
};

for item, values in foodOverrides {
    if (!isNull(item)) {
        item.foodValues.hunger = values[0];
        item.foodValues.saturationModifier = values[1];
    }
}

// ============================================================
// === ALWAYS EDIBLE DESSERTS ===
// === Edible sweet treats, pastries, and slices that can be ===
// === enjoyed anytime regardless of the player's hunger bar ===
// ============================================================
val desserts as IItemStack[] = [
    // Cookies & Small Sweet Bites
    <minecraft:cookie>,
    <farmersdelight:sweet_berry_cookie>,
    <farmersdelight:honey_cookie>,
    <ends_delight:chorus_cookie>,
    <twilightdelight:torchberry_cookie>,
    <twilightdelight:chocolate_wafer>,

    // Cake & Pie Slices (Elevated to Tier 3)
    <farmersdelight:cake_slice>,
    <farmersdelight:apple_pie_slice>,
    <farmersdelight:sweet_berry_cheesecake_slice>,
    <farmersdelight:chocolate_pie_slice>,
    <farmersdelight:pumpkin_pie_slice>,
    <ends_delight:chorus_fruit_pie_slice>,
    <twilightdelight:aurora_cake_slice>,
    <twilightdelight:torchberry_cake_slice>,
    <twilightdelight:phytochemical_cake_slice>,
    <twilightdelight:glacier_cake_slice>,
    <twilightdelight:torchberry_pie_slice>,
    <twilightdelight:aurora_pie_slice>,
    <extradelightlegacy:cheesecake_slice>,
    <extradelightlegacy:apple_cheesecake_slice>,
    <extradelightlegacy:caramel_cheesecake_slice>,
    <extradelightlegacy:chocolate_cheesecake_slice>,
    <extradelightlegacy:glow_berry_cheesecake_slice>,
    <extradelightlegacy:honey_cheesecake_slice>,
    <extradelightlegacy:pumpkin_cheesecake_slice>,
    <extradelightlegacy:sweet_berry_pie_slice>,
    <extradelightlegacy:glow_berry_pie_slice>,
    <extradelightlegacy:pumpkin_pie_slice>,
    <extradelightlegacy:chocolate_cake_slice>,

    // Ice Cream & Custards
    <extradelightlegacy:honey_custard>,
    <extradelightlegacy:honey_ice_cream>,
    <extradelightlegacy:mint_chip_ice_cream>,
    <twilightdelight:honey_113>,
    <twilightdelight:aurora_ice_cream>,
    <twilightdelight:torchberry_ice_cream>,
    <twilightdelight:phytochemical_ice_cream>,
    <twilightdelight:glacier_ice_cream>,

    // Sweet Treats & Gelatins
    <nethers_delight_legacy:magma_gelatin>,
    <twilightdelight:berry_stick>,
    <farmersdelight:fruit_salad>,
    <ends_delight:stuffed_rice_cake>,

    // Sweet Pastries & Feasts Servings
    <extradelightlegacy:french_toast>,
    <extradelightlegacy:cinnamon_rolls>,
    <extradelightlegacy:pumpkin_roll>,
    <extradelightlegacy:apple_crisp>,
    <extradelightlegacy:stuffed_apple>,
    <extradelightlegacy:lava_cake>
];

for dessert in desserts {
    if (!isNull(dessert)) {
        dessert.foodValues.alwaysEdible = true;
    }
}
